{% set name = "syncthing" %}
{% set version = "1.18.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/releases/download/v{{ version }}/{{ name }}-source-v{{ version }}.tar.gz
  sha256: 3f6b8e87a59e72ab3389d89364524e6abec454d4c36aaf3e334ac6fe37915584

build:
  number: 0
  script:
    - go run build.go -version v{{ version }} -no-upgrade install
    - mv bin/* $PREFIX  # [not win]
    - move bin\* %PREFIX%  # [win]

requirements:
  build:
    - {{ compiler('go') }}

test:
  commands:
    - which syncthing  # [not win]
    - where syncthing  # [win]
    - syncthing --help

about:
  home: https://github.com/syncthing/syncthing
  license: MPL-2.0
  summary: Open Source Continuous File Synchronization
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tao-j
