{% set name = "syncthing" %}
{% set version = "1.25.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/releases/download/v{{ version }}/{{ name }}-source-v{{ version }}.tar.gz
  sha256: e25199e870236216b8409f4c30735c177c83d9eb7f77474c8a9d0c6739789ea1

build:
  number: 0
  script:
    - go run build.go -version v{{ version }} -no-upgrade install
    - mkdir -p $PREFIX/bin  # [not win]
    - mv bin/* $PREFIX/bin  # [not win]
    - mkdir %LIBRARY_BIN%        # [win]
    - move bin\* %LIBRARY_BIN%\  # [win]

requirements:
  build:
    - {{ compiler('go') }}

test:
  commands:
    - which syncthing  # [not win]
    - where syncthing  # [win]
    - syncthing --help

about:
  home: https://github.com/syncthing/syncthing
  license: MPL-2.0
  summary: Open Source Continuous File Synchronization
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tao-j
