{% set name = "syncthing" %}
{% set version = "1.18.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/releases/download/v{{ version }}/{{ name }}-source-v{{ version }}.tar.gz
  sha256: afe2ae979da3b4f1af8aeabd7e1704807242913b516e0b6585510821c9d6d4f2

build:
  number: 0
  script:
    - go run build.go -version v{{ version }} -no-upgrade install
    - mv bin/* $PREFIX  # [not win]
    - move bin\* %PREFIX%  # [win]

requirements:
  build:
    - {{ compiler('go') }}

test:
  commands:
    - which syncthing  # [not win]
    - where syncthing  # [win]
    - syncthing --help

about:
  home: https://github.com/syncthing/syncthing
  license: MPL-2.0
  summary: Open Source Continuous File Synchronization
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tao-j
