{% set name = "syncthing" %}
{% set version = "2.0.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/releases/download/v{{ version }}/{{ name }}-source-v{{ version }}.tar.gz
  sha256: fec36ce20bbcd6e6d1cb70cfb0af7a45c6221581361d9bb92807389b24703a02

build:
  number: 0
  script:
    - go run build.go -version v{{ version }} -no-upgrade install
    - mkdir -p $PREFIX/bin  # [not win]
    - mv bin/* $PREFIX/bin  # [not win]
    - mkdir %LIBRARY_BIN%        # [win]
    - move bin\* %LIBRARY_BIN%\  # [win]

requirements:
  build:
    - {{ compiler('go') }}

test:
  commands:
    - which syncthing  # [not win]
    - where syncthing  # [win]
    - syncthing --help

about:
  home: https://github.com/syncthing/syncthing
  license: MPL-2.0
  summary: Open Source Continuous File Synchronization
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tao-j
