context:
  version: "2.1.5"

package:
  name: syncthing
  version: ${{ version }}

source:
  url: https://github.com/syncthing/syncthing/archive/v${{ version }}.tar.gz
  sha256: 1b3e217022848b65a1b7ececa4d5e752fc044b4e8643befa1f9a8a9dc9b2bbbf

build:
  number: 0
  script:
    - go-licenses save ./cmd/syncthing --save_path library_licenses --ignore github.com/syncthing/ --ignore github.com/jackpal/go-nat-pmp
    - go run build.go -version v${{ version }} -no-upgrade build
    - if: unix
      then: install -D -m0755 -t "$PREFIX/bin" syncthing
      else: move syncthing.exe %LIBRARY_BIN%\

requirements:
  build:
    - go-licenses
    - ${{ compiler("go-cgo") }}
    - if: unix
      then:
        - ${{ compiler("c") }}
        - ${{ stdlib("c") }}
      else:
        - ${{ compiler("m2w64_c") }}
        - ${{ stdlib("m2w64_c") }}
    - if: osx
      then:
        - uutils-coreutils

tests:
  - script:
      - syncthing --version
      - syncthing --help
  - package_contents:
      strict: true
      bin:
        - syncthing

about:
  homepage: https://github.com/syncthing/syncthing
  repository: https://github.com/syncthing/syncthing
  summary: Open Source Continuous File Synchronization
  license: MPL-2.0
  license_file:
    - LICENSE
    - library_licenses/

extra:
  recipe-maintainers:
    - tao-j
    - XhstormR
